<embed 
    type="application/x-vlc-plugin" 
    pluginspage="http://www.videolan.org" 
    version="VideoLAN.VLCPlugin.2"
    width="50%"
    height="50%"
    target="rtsp://ukrida:ukrida@192.168.14.54/12"
    id="vlc">
</embed>

<embed 
    type="application/x-vlc-plugin" 
    pluginspage="http://www.videolan.org" 
    version="VideoLAN.VLCPlugin.2"
    width="50%"
    height="50%"
    target="rtsp://ukrida:ukrida@192.168.14.55/12"
    id="vlc">
</embed>